Добавляет функции
htmlacademy-javascript/557625-keksobooking-23 pull request #2
Opened 2021-05-30 07:32 UTC by ZaicevID

2021-05-30 13:51 UTC, yulllll reviewed
посмотри результаты проверки линтера

2021-06-01 05:46 UTC, yulllll requested changes

2021-06-01 05:46 UTC, yulllll commented on js/main.js
> +const RANDOM_NUMBER = function (min, max) {
Не соблюдён критерий наименования функций

2021-06-01 05:46 UTC, yulllll commented on js/main.js
> +RANDOM_NUMBER(1, 3);
Вызовы, которые не используются лучше убрать из кода

2021-06-01 05:46 UTC, yulllll commented on js/main.js
> +    return 'Диапазон может быть только положительный';
Лучше кидать ошибку throw new Error, чем возвращать строку

2021-06-01 07:20 UTC, ZaicevID commented on js/main.js
> +const RANDOM_NUMBER = function (min, max) {
Поправил

2021-06-01 07:29 UTC, ZaicevID commented on js/main.js
> +RANDOM_NUMBER(1, 3);
RANDOM_NUMBER(1, 3); правильно понял, это убрать нужно? Будет тест ругаться...

2021-06-01 07:40 UTC, ZaicevID commented on js/main.js
> +    return 'Диапазон может быть только положительный';
переделал

2021-06-01 15:28 UTC, yulllll commented on js/main.js
> +RANDOM_NUMBER(1, 3);
ничего страшного - пока задача создать неиспользуемую функцию

2021-06-01 17:16 UTC, merged